# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  nuget-psgallery:
    type: nuget-feed
    url: https://www.powershellgallery.com/api/v2
    replaces-base: true
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries:
      - nuget-psgallery
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
